name: GetBack
main: ac.plugin.GetBack
version: 1.2.0
api-version: 1.18
description: Easily come back to your death place
author: a13ssandr0
website: https://github.com/a13ssandr0/GetBack
load: POSTWORLD
commands:
  back:
    description: 回到案发现场
    usage: /back